### ISSUE TITLE
Eu como cidadão brasileiro desejo manter-me atualizado com as propostas favoritas, para acompanhar suas mudanças.

### ISSUE THREAD

**Issue by marcowilliam** [fga-gpp-mds/2016.2-CidadeDemocratica#21]

**Comment by luisfrvilela** [comment]
- [ ] O usuario deve receber notificacoes de atualizacao das propostas favoritas
- [ ] Ao clicar na notificacao o aplicativo deve abrir a pagina da proposta diretamente
