### ISSUE TITLE
Eu como desenvolvedor desejo implementar o deploy automático na conta do cliente, para acelerar a distribuição.

### ISSUE THREAD

**Issue by marcowilliam** [fga-gpp-mds/2016.2-CidadeDemocratica#22]

**Comment by luisfrvilela** [comment]
**Critérios de Aceitação**
- [ ] O deploy deverá ser realizado na conta oficial do Cidade Democrática.

**Comment by luisfrvilela** [comment]
**Atividades**

-  Atividade 1
-  Atividade 2

**Comment by marcowilliam** [comment]
Esperando a chave de acesso gerada pela API do google play por parte do cliente @ricardopoppi
