### ISSUE TITLE
Eu como cidadão brasileiro desejo compartilhar uma proposta em redes sociais para disseminar a ideia da proposta e ajudá-la a ser concretizada.

### ISSUE THREAD

**Issue by marcowilliam** [fga-gpp-mds/2016.2-CidadeDemocratica#23]

**Comment by luisfrvilela** [comment]
**Atividades**

-  Atividade 1
-  Atividade 2

**Comment by luisfrvilela** [comment]
**Critérios de Aceitação**
- [x] O texto do compartilhamento deverá conter título da proposta, descrição e link do site do Cidade Democrática.
